### ISSUE TITLE
creation of User Model

### ISSUE THREAD

**Issue by Dinesh100K** [ManVTish/rails_cart#1]
Schema:
first_name
last_name
address
email_id
phone
city
state
zip

**Comment by ManVTish** [comment]
PR is created [(https://github.com/ManVTish/rails_cart/pull/4](https://github.com/ManVTish/rails_cart/pull/4) for this issue.

**Comment by ManVTish** [comment]
Used this documentation for tailwindcss setup [https://tailwindcss.com/docs/guides/ruby-on-rails](https://tailwindcss.com/docs/guides/ruby-on-rails)
Used css code for tailwind from here [https://www.honeybadger.io/blog/tailwind-css-rails/](https://www.honeybadger.io/blog/tailwind-css-rails/)

**Comment by ManVTish** [comment]
command used for generating User
`rails g scaffold users first_name:string last_name:string email:string phone:integer address:string city:string state:string zip:integer`
