### ISSUE TITLE
Adding pry gem for testing

### ISSUE THREAD

**Issue by Dinesh100K** [ManVTish/rails_cart#6]

**Comment by Dinesh100K** [comment]
Adding `pry-byebug` gem. because it has more downloads than `pry-rails` 
Combine 'pry' with 'byebug'. Adds 'step', 'next', 'finish', 'continue' and 'break' commands to control execution.

**Comment by Dinesh100K** [comment]
closes #7

**Comment by ManVTish** [comment]
This issue was addressed through PR #7
